name: 文心的博客
author: wenxin919220.github.io                                            #这是什么？？？？？？？？？？？？？？？
#baseurl: /liangzai.pub
keywords: j                                                               #这在哪里显示？？？？？？？？？？？
description: 有些路注定要一个人走！
github: https://github.com/wenxin919220
email: 2135482699@qq.com


encoding: utf-8
#highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
